// Generated by scripts/sync-products.mjs from the Printify and Printful stores.
// Do not edit by hand: changes here are replaced at the next sync.
// Last updated 2026-10-01T07:34:07.872Z
window.DELLIS_PRODUCTS = [
  {
    "name": "Mighty Diver Kids T-Shirt – Comfort Meets Adventure",
    "price": "$17.63",
    "group": "kids",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5eeab31108c310859ad/35031/266/mighty-diver-kids-t-shirt-comfort-meets-adventure.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534560"
  },
  {
    "name": "Dive into Lunch with the Mighty Diver Lunchbox!",
    "price": "$44.86",
    "group": "gear",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5efab31108c310859ae/74699/19826/dive-into-lunch-with-the-mighty-diver-lunchbox.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534559"
  },
  {
    "name": "Colorful Heart Stainless Steel Water Bottle with Straw – 20oz",
    "price": "$22.12",
    "group": "gear",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5efab31108c310859af/87246/57450/colorful-heart-stainless-steel-water-bottle-with-straw-20oz.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534557"
  },
  {
    "name": "Toddler Long Sleeve Tee - 'Forever My Puppy'  🐾",
    "price": "$21.58",
    "group": "kids",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f0ab31108c310859b0/71448/101068/toddler-long-sleeve-tee-forever-my-puppy.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534556"
  },
  {
    "name": "Women's Forever Love Tee - Heart Design",
    "price": "$20.91",
    "group": "adults",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f0ab31108c310859b1/33867/101402/womens-forever-love-tee-heart-design.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534555"
  },
  {
    "name": "Cropped Fleece Pullover with 'Forever' Design🐾",
    "price": "$48.51",
    "group": "adults",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f1ab31108c310859b2/72753/105336/cropped-fleece-pullover-with-forever-design.jpg?camera_label=on-person",
    "link": "https://dellis-store.printify.me/product/32534554"
  },
  {
    "name": "Cute Dog Graphic Women's Tee 🐾",
    "price": "$15.89",
    "group": "adults",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f2ab31108c310859b3/17979/88/cute-dog-graphic-womens-tee.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32534553"
  },
  {
    "name": "Mighty Diver Clogs – Adventure-Ready Footwear for Kids",
    "price": "$15.46",
    "group": "kids",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f3ab31108c310859b5/109711/105326/mighty-diver-clogs-adventure-ready-footwear-for-kids.jpg?camera_label=context-2",
    "link": "https://dellis-store.printify.me/product/32534552"
  },
  {
    "name": "Mighty Traveler Passport Wallet, Travel Accessory for Adventurers",
    "price": "$7.73",
    "group": "gear",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5f3ab31108c310859b4/78539/38318/mighty-traveler-passport-wallet-travel-accessory-for-adventurers.jpg?camera_label=front-vertical",
    "link": "https://dellis-store.printify.me/product/32534551"
  },
  {
    "name": "Youth Hooded Towel - Mighty Diver",
    "price": "$32.71",
    "group": "kids",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5edab31108c310859aa/91884/62423/youth-hooded-towel-mighty-diver.jpg?camera_label=on-person-back-1",
    "link": "https://dellis-store.printify.me/product/32526679"
  },
  {
    "name": "Dive into Adventure with the Mighty Diver Backpack!",
    "price": "$50.94",
    "group": "gear",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5edab31108c310859ab/61364/2984/dive-into-adventure-with-the-mighty-diver-backpack.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32526678"
  },
  {
    "name": "Cozy Up your Toddler in the Mighty Diver Kids Sweatshirt",
    "price": "$23.40",
    "group": "kids",
    "store": "printify",
    "image": "https://images-api.printify.com/mockup/6abbb5eeab31108c310859ac/113783/110548/cozy-up-your-toddler-in-the-mighty-diver-kids-sweatshirt.jpg?camera_label=front",
    "link": "https://dellis-store.printify.me/product/32526677"
  },
  {
    "name": "Youth Short Sleeve T-Shirt",
    "price": "From $16.00",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-307-6abbb3ccedd69__360",
    "link": "https://dellis.printful.me/product/youth-short-sleeve-t-shirt"
  },
  {
    "name": "Youth classic tee",
    "price": "From $11.50",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-732-6abbb38acd174__360",
    "link": "https://dellis.printful.me/product/youth-classic-tee"
  },
  {
    "name": "All-over print long sleeve midi dress",
    "price": "From $42.50",
    "group": "adults",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-589-68ff9016c64c5__360",
    "link": "https://dellis.printful.me/product/all-over-print-long-sleeve-midi-dress"
  },
  {
    "name": "Youth long sleeve tee",
    "price": "From $20.50",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-511-670a9bc46bf00__360",
    "link": "https://dellis.printful.me/product/youth-long-sleeve-tee-670a9bc4c16cf"
  },
  {
    "name": "Kids Rash Guard",
    "price": "From $27.50",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-368-670a9b9c0c743__360",
    "link": "https://dellis.printful.me/product/kids-rash-guard"
  },
  {
    "name": "3/4 sleeve raglan shirt",
    "price": "From $21.00",
    "group": "adults",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-233-670a9b2cf1e16__360",
    "link": "https://dellis.printful.me/product/34-sleeve-raglan-shirt"
  },
  {
    "name": "Leggings",
    "price": "From $27.50",
    "group": "adults",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-189-670a9acda3532__360",
    "link": "https://dellis.printful.me/product/leggings"
  },
  {
    "name": "Men's Champion Long Sleeve Shirt",
    "price": "From $29.50",
    "group": "adults",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-374-670a9aa47e16b__360",
    "link": "https://dellis.printful.me/product/mens-champion-long-sleeve-shirt"
  },
  {
    "name": "Youth long sleeve tee",
    "price": "From $20.50",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-511-670a9a77523ee__360",
    "link": "https://dellis.printful.me/product/youth-long-sleeve-tee"
  },
  {
    "name": "Men's Champion T-Shirt",
    "price": "From $27.00",
    "group": "adults",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-373-670a99bab4709__360",
    "link": "https://dellis.printful.me/product/mens-champion-t-shirt"
  },
  {
    "name": "Youth baseball cap",
    "price": "From $21.50",
    "group": "kids",
    "store": "printful",
    "image": "https://cdn.printful.me/t/quick-stores/products/w168/14529763-429-670a8c545690f__360",
    "link": "https://dellis.printful.me/product/youth-baseball-cap"
  }
];
